import type { PaginatedResult, ResearcherDto } from "@repo/contracts";

export const DEFAULT_RESEARCHERS_RESULT: PaginatedResult<ResearcherDto> = {
  data: [
    {
      id: "r-1",
      slug: "jiawei-han",
      name: "Dr. Jiawei Han",
      email: "hanj@illinois.edu",
      department: "Computer Science",
      title: "Michael Aiken Chair Professor",
      bio: "World-renowned pioneer in data mining, text mining, and information network analysis.",
      profileUrl:
        "https://siebelschool.illinois.edu/about/people/all-faculty/hanj",
      photoUrl: null,
      worksCount: 950,
      citedByCount: 198000,
      keywords: [
        "Data Mining",
        "Text Mining",
        "Information Networks",
        "LLM Extraction",
        "Knowledge Graphs",
      ],
    },
    {
      id: "r-2",
      slug: "sarita-adve",
      name: "Dr. Sarita Adve",
      email: "sadve@illinois.edu",
      department: "Computer Science",
      title: "Richard T. Cheng Professor",
      bio: "Pioneering computer architect leading Illinois XR and memory consistency models research.",
      profileUrl:
        "https://siebelschool.illinois.edu/about/people/all-faculty/sadve",
      photoUrl: null,
      worksCount: 220,
      citedByCount: 24000,
      keywords: [
        "Computer Architecture",
        "Memory Consistency",
        "Extended Reality (XR)",
        "Parallel Computing",
      ],
    },
    {
      id: "r-3",
      slug: "marc-snir",
      name: "Dr. Marc Snir",
      email: "snir@illinois.edu",
      department: "Computer Science",
      title: "Professor Emeritus",
      bio: "Key contributor to the Message Passing Interface (MPI) standard and scalable supercomputing architecture.",
      profileUrl:
        "https://siebelschool.illinois.edu/about/people/all-faculty/snir",
      photoUrl: null,
      worksCount: 310,
      citedByCount: 29000,
      keywords: [
        "High Performance Computing",
        "MPI",
        "Supercomputing",
        "Parallel Algorithms",
      ],
    },
    {
      id: "r-4",
      slug: "nancy-m-amato",
      name: "Dr. Nancy M. Amato",
      email: "namato@illinois.edu",
      department: "Computer Science",
      title: "Abel Bliss Professor & Department Head",
      bio: "Leading researcher in motion planning, robotics, computational biology, and parallel computing.",
      profileUrl:
        "https://siebelschool.illinois.edu/about/people/all-faculty/namato",
      photoUrl: null,
      worksCount: 380,
      citedByCount: 21500,
      keywords: [
        "Robotics",
        "Motion Planning",
        "Computational Biology",
        "Parallel Algorithms",
      ],
    },
    {
      id: "r-5",
      slug: "stephen-long",
      name: "Dr. Stephen Long",
      email: "slong@illinois.edu",
      department: "Crop Sciences & Plant Biology",
      title: "Ikenberry Endowed Chair",
      bio: "Pioneering research in improving crop photosynthetic efficiency for global food and bioenergy security.",
      profileUrl: "https://cropsciences.illinois.edu/directory/profile/slong",
      photoUrl: null,
      worksCount: 460,
      citedByCount: 45000,
      keywords: [
        "Photosynthesis",
        "Crop Yield",
        "Climate Change Mitigation",
        "Bioenergy Crops",
      ],
    },
  ],
  meta: {
    total: 5,
    page: 1,
    limit: 10,
    totalPages: 1,
    hasNextPage: false,
    hasPrevPage: false,
  },
};
